Use a custom http.Client for c2cx.Client and set a timeout
uberfurrer/tradebot pull request #83
Opened 2018-03-25 09:32 UTC by Vavilen

For issue #76

2018-03-26 11:10 UTC, gz-c requested changes

2018-03-26 11:10 UTC, gz-c commented on exchange/c2cx/api.go
> +	dialTimeout         = 5 * time.Second
Change it to 60, 120, 60 seconds

2018-03-26 20:38 UTC, Vavilen commented on exchange/c2cx/api.go
> +	dialTimeout         = 5 * time.Second
@gz-c, done.

2018-03-27 04:42 UTC, gz-c approved these changes

2018-03-27 04:42 UTC, merged