C2CX API integration tests
uberfurrer/tradebot pull request #87
Opened 2018-04-15 09:04 UTC by Vavilen

Completed test cases
- [x] get_orderbook
- [x] get_balance_summary
- [x] create_order
- [x] get_order_info
- [x] get_order_info_all
- [x] cancel_order
- [x] cancel_multiple
- [x] cancel_all
- [x] limit_buy
- [x] limit_sell
- [ ] market_buy
- [ ] market_sell
- [x] get_ticker
- [x] get_order_by_status
- [x] get_order_by_status_paged

2018-04-15 09:11 UTC, Vavilen commented
@gz-c,  tests failed because there is no the config file. I will think out about ENV vars as the alternative for the config file.

2018-04-16 08:18 UTC, gz-c commented
You can add a hidden file with test config such as ".test.cfg" and specify to use that in travis

2018-04-16 08:19 UTC, gz-c requested changes

2018-04-16 08:19 UTC, gz-c commented on exchange/c2cx/api.go
> +	//fmt.Println("data in GetOrderbook:\n" + string(data) + "\n===============\n\n")
delete

2018-04-16 08:19 UTC, gz-c commented on exchange/c2cx/api.go
> +	//fmt.Println("data in GetBalanceSummary:\n" + string(data) + "\n===============\n\n")
delete

2018-04-16 08:19 UTC, gz-c commented on exchange/c2cx/c2cx.go
> +	PageCount int     `json:"pageCount,omitempty"`
page is different from pageCount, why is this changed?

2018-04-16 08:19 UTC, gz-c commented on exchange/order.go
> +// MarketOrder is a one order in stock
what is this for?

2018-04-17 17:39 UTC, Vavilen commented on exchange/order.go
> +// MarketOrder is a one order in stock
Moved it to the integration_test.go file. It is useful for unmarshaling orderbook response in a test.

2018-04-17 17:47 UTC, Vavilen commented on exchange/c2cx/c2cx.go
> +	PageCount int     `json:"pageCount,omitempty"`
I thought that this param is useful to know it is necessary to know if there are more pages.
Added both params.

2018-04-18 01:39 UTC, gz-c requested changes

2018-04-18 01:39 UTC, gz-c commented on exchange/c2cx/cli/c2cx.go
> +				handleResult(c2cx.Orders{Orders: orders, PageCount: pageCount}, err)
Do you need to populate Page?

2018-04-18 01:39 UTC, gz-c commented on exchange/c2cx/integration_test.go
> +				require.True(t, bid.Volume.Cmp(decimal.New(0, 10)) > 0)
could do `.GreaterThan(decimal.Zero)`

2018-04-18 01:39 UTC, gz-c commented on exchange/c2cx/integration_test.go
> +			require.True(t, len(resp.Frozen) > 0)
can you check that the final calculated balance (which subtracts frozen) succeeds and have valid values (`>=0`)?

2018-04-21 02:26 UTC, gz-c commented
@Vavilen some requested changes and the build fails

2018-04-22 01:15 UTC, gz-c requested changes

2018-04-22 01:15 UTC, gz-c commented on exchange/c2cx/.testConfig/.test.toml
> +secret = "4D7683C9-BE09-44B8-AE32-08070A2F7540"
probably should not add this to the repo directly, we can add it to travis as a secret environment variable and add a travis step to write config file

also, the folder name should not be `.testConfig`, don't use mixed case for folder names

2018-04-22 01:15 UTC, gz-c commented on exchange/c2cx/api.go
> +		fmt.Println(string(data))
remove

2018-04-22 01:15 UTC, gz-c commented on exchange/c2cx/c2cx.go
> +	PagesCount int     `json:"pagesCount,omitempty"`
is it pageCount or pagesCount?

2018-04-22 01:15 UTC, gz-c commented on exchange/c2cx/cli/c2cx.go
> +	if os.Getenv("TEST_EXCHANGE_CONFIG") == "" {
Do not have test specific code here.  Either name the envvar something like `EXCHANGE_API_CONFIG` or add a `-c <config>` CLI flag (https://github.com/skycoin/teller has an example of this)

2018-04-22 19:21 UTC, Vavilen commented on exchange/c2cx/.testConfig/.test.toml
> +secret = "4D7683C9-BE09-44B8-AE32-08070A2F7540"
@gz-c , should I use travis functional (didn't find any) for saving data from a secret environment variable or run an external bash script from travis step, which:
1. reads data from a travis secret environment variable
2. saves data to the file with some path.
3. sets path to a config file to an environment variable EXVHANGE_API_CONFIG

2018-04-22 19:27 UTC, Vavilen commented on exchange/c2cx/c2cx.go
> +	PagesCount int     `json:"pagesCount,omitempty"`
@gz-c , my bad. pageCount is correct.

2018-04-23 02:29 UTC, gz-c commented on exchange/c2cx/.testConfig/.test.toml
> +secret = "4D7683C9-BE09-44B8-AE32-08070A2F7540"
I added these as envvars in the travis environment as C2CX_API_KEY and C2CX_API_SECRET, you can use them to write a config file during the travis setup

2018-04-23 02:30 UTC, gz-c commented on exchange/c2cx/.testConfig/.test.toml
> +secret = "4D7683C9-BE09-44B8-AE32-08070A2F7540"
You should squash your commits into one to remove these keys from the commit history

2018-05-02 03:53 UTC, gz-c approved these changes

2018-05-02 03:53 UTC, merged